accounts/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken.views import ObtainAuthToken

from django.contrib.auth import views as auth_views
from accounts import views

from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'accounts'
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    # API Endpoint
    #path('auth/', ObtainAuthToken.as_view()),
    path('api-user/', include('rest_framework.urls', namespace='rest_framework')),
    path('auth/', views.LoginView.as_view(), name='login'),

]

guia_col_project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path

from guicolapp import views

urlpatterns = [
    url(r'^$', views.guias, name='home'),
    path('accounts/', include(
        'accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('api/', include('guicolapp.urls')),
    
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from phone_field import PhoneField


# Profile model that extends
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    phone = PhoneField(blank=True)

accounts/forms.py
from django import forms

accounts/views.py
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import Profile
from rest_framework import viewsets
from django.contrib.auth import authenticate
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAdminUser, IsAuthenticated, AllowAny

from .serializers import UserSerializer
from django.core import serializers
from rest_framework import status
from rest_framework.authtoken.models import Token
from rest_framework.views import APIView
from rest_framework.response import Response

from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser

# View of the API accounts endpoint MUST BE ADMIN USER!


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed, created or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class LoginView(APIView):
    permission_calsses = (AllowAny,)

    def post(self, request, *args, **kwargs):
        data = request.data

        user = authenticate(username=data.get('username'),
                            password=data.get('password'))

        if user:
            token, _ = Token.objects.get_or_create(user=user)
            return Response({'token': token.key, 'id': user.pk,
                             'username': user.username,
                             'fname': user.profile.first_name,
                             'lname': user.profile.last_name,
                             'email': user.email,
                             'phone': str(user.profile.phone)
                             }, status=200)

        return Response(status=400)

accounts/templates/accounts/login.html
{% block content %}
<div style="text-align:center" class="col-md-9 mx-auto mb-5 mt-xl-5">
  <h2>Iniciar Sesión</h2>
</div>

{% if form.errors %}
<p style="color: red">Your username and password didn't match. Please try again.</p>
{% endif %}
<div style="text-align:center">
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}<br>
      {% for error in field.errors %}
      <p style="color: red">{{ error }}</p>
      {% endfor %}
      {% if field.help_text %}
      <p><small style="color: grey">{{ field.help_text }}</small></p>
      {% endif %}
    </p>
    {% endfor %}
    <button type="submit">Login</button>
  </form>
</div>

{% endblock %}